//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.WindowsReboot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class DuckSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DuckSettings defaultInstance = ((DuckSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DuckSettings())));
        
        public static DuckSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delay")]
        public global::DustInTheWind.WindowsReboot.ActionTimeType ActionTime_Type {
            get {
                return ((global::DustInTheWind.WindowsReboot.ActionTimeType)(this["ActionTime_Type"]));
            }
            set {
                this["ActionTime_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2012-12-22")]
        public global::System.DateTime ActionTime_DateTime {
            get {
                return ((global::System.DateTime)(this["ActionTime_DateTime"]));
            }
            set {
                this["ActionTime_DateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ActionTime_Hours {
            get {
                return ((int)(this["ActionTime_Hours"]));
            }
            set {
                this["ActionTime_Hours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ActionTime_Minutes {
            get {
                return ((int)(this["ActionTime_Minutes"]));
            }
            set {
                this["ActionTime_Minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ActionTime_Seconds {
            get {
                return ((int)(this["ActionTime_Seconds"]));
            }
            set {
                this["ActionTime_Seconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ring")]
        public global::DustInTheWind.WindowsReboot.ActionType ActionType {
            get {
                return ((global::DustInTheWind.WindowsReboot.ActionType)(this["ActionType"]));
            }
            set {
                this["ActionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ForceClosingPrograms {
            get {
                return ((bool)(this["ForceClosingPrograms"]));
            }
            set {
                this["ForceClosingPrograms"] = value;
            }
        }
    }
}
